### PR TITLE
COSMO surface visualization

### PR DESCRIPTION
**Pull request by kierannp**
Added ability to visualize cosmo surface charges and chemical graph with plotly

### CODE REVIEW

**Comment by simonmb** [comment]
Hey, thanks for the nice functionality.

There is a new update of the input_parsers.py which has not yet been migrated to the python version of the code here: https://github.com/TUHH-TVT/openCOSMO-RS_conformer_pipeline/blob/main/input_parsers.py

Would you be able to change your PR to integrate the new parser into the python version of openCOSMO-RS and then add your functionality directly into the new SigmaProfileParser?

I would recommend using the rdkit.Chem.rdmolfiles.MolFromXYZBlock functionality built into rdkit to get the bonds and be able to plot them. This would lead to a much more general function capable of platting any type of 3d structure independent of which atom-atom connections are available.

**Comment by simonmb** [comment]
I just integrated the new input_parsers.py, would you be available to change the PR to add your feature into the input_parsers.py?

**Comment by kierannp** [comment]
Yeah I'll get this done in the next few hours.

**Comment by kierannp** [comment]
> I just integrated the new input_parsers.py, would you be available to change the PR to add your feature into the input_parsers.py?

Unfortunately this isn't currently possible as far as I can tell. XYZ files only contain atom coordinates not bond connectivity information. You can estimate the connectivity in using rdkit but I believe it requires geometry optimization which might mess with the structure. We can either not draw bonds or use predefined dictionary method.

**Comment by simonmb** [comment]
Hi, unfortunately the xyz2mol implementation in rdkit takes a string or a file as input. You could modify the function save_to_xyz_file in the input_parsers.py to be able to return what is normally written to a file as a string. Or you creat the XYZ block string similarly to save_to_xyz_file and then save it to a variable. This you feed to MolFromXYZBlock ,  this will return an rdkit molecule with all bonds with the atoms in the order as specified in the input file. With that you should be able to plot it.

**Comment by kierannp** [comment]
rdkit has [rdkit.chem.MolFromXYZFile](https://www.rdkit.org/docs/source/rdkit.Chem.rdmolfiles.html#rdkit.Chem.rdmolfiles.MolFromXYZFile) but rdkit doesn't have a built in method for estimating bond distance. I just tested and the same issue arises from rdkit.Chem.MolFromXYZBlock, unless I am doing something wrong...
`parser.save_to_xyz_file('cosmo_surface.xyz')
with open('cosmo_surface.xyz', 'r') as file:
    xyz_string = file.read()
mol = Chem.MolFromXYZBlock(xyz_string)
mol.GetConformer()
list(mol.GetBonds())`
Which returns [].

XYZ files don't contain bonding information so rdkit doesn't doesn't calculate them automatically.

**Comment by simonmb** [comment]
You need to call `DetermineBonds`. I added a new function to input_parsers.py allowing to output the XYZ block to str. This works for me:

```python
from rdkit import Chem
from rdkit.Chem import rdDetermineBonds

spp = SigmaProfileParser('ethanol.orcacosmo')
mol = Chem.MolFromXYZBlock(spp.save_to_xyz())
rdDetermineBonds.DetermineBonds(mol, charge=0)
print(list(mol.GetBonds()))
```

**Comment by kierannp** [comment]
> You need to call `DetermineBonds`. I added a new function to input_parsers.py allowing to output the XYZ block to str. This works for me:
> 
> ```python
> from rdkit import Chem
> from rdkit.Chem import rdDetermineBonds
> 
> spp = SigmaProfileParser('ethanol.orcacosmo')
> mol = Chem.MolFromXYZBlock(spp.save_to_xyz())
> rdDetermineBonds.DetermineBonds(mol, charge=0)
> print(list(mol.GetBonds()))
> ```

Awesome! didn't know about this feature. Should be good now!

**Pull request merged**
